inherit_from: rollout.yaml            # reuse the same model + tool stack
data_module:
  _target_: verl.data.jsonl.JsonlDataModule
  path: "data/kernelbench_holdout.jsonl"
  text_key: "prompt"
  batch_size: 1

evaluate_only: true                   # Verl runs rollouts, prints metrics
num_rollouts: 20                      # one per task
save_stats_to: "eval_results.json"

