actor_rollout_ref:
  rollout:
    name: "sglang"
    multi_turn: true
    tool_kwargs:
      tools_config_file: "tools/kernel_tool.yaml"
    context_postprocessor:
      _target_: verl.utils.context_reducer.retain_last_n
      n: 6
    val_kwargs:
      max_new_tokens: 2048
    engine_kwargs:
      vllm:
        enforce_eager: true
  model:
    path: "Qwen/Qwen3-4B"

n_actors: 4

algorithm:
  name: ppo
  gamma: 0.4
  adv_estimator: grpo
  clip_range: 0.2
  vf_coef: 1.0
  learning_rate: 1e-5
  rollout_batch_size: 8

custom_reward_function:
  path: "kevin_reward.py"
  name: "compute_score"

# Export the reset command to subprocesses
env:
  GPU_RESET_CMD: "nvidia-smi --gpu-reset -i 0"
